# Generated by Django 3.1.5 on 2021-01-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WyvernPosters', '0002_auto_20210121_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='imagen',
            field=models.ImageField(upload_to='posters'),
        ),
    ]
