# Generated by Django 3.1.5 on 2021-04-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WyvernForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforum',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replyforum',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replyforum',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
